const EmailText = [
{
    "mittente": "Simona",
    "titolo": "Result of the test1",
    "emailHead": "Hey there!",
	"email": "Hey there! Thanks for coming over on such short notice.",
	"emailFooter": "Best wishes.",
    "videoPath": "media/Weeks/Week1/VideoRisposte/“I throw food..”.mp4",
    "open" : false,
    "display": false,
},
{
    "mittente": "Simona",
    "titolo": "Result of the test2",
    "emailHead": "Hey there!",
	"email": "Hey there! Thanks for coming over on such short notice.",
	"emailFooter": "Best wishes.",
    "videoPath": "media/Weeks/Week1/VideoRisposte/“When choosing to buy products, I often consider the sustainability of their production processes”.mp4",
    "open" : false,
    "display": false,
},
{
    "mittente": "Simona",
    "titolo": "Result of the test3",
    "emailHead": "Hey there!",
	"email": "Hey there! Thanks for coming over on such short notice.",
	"emailFooter": "Best wishes.",
    "videoPath": "media/Weeks/Week1/VideoRisposte/“I minimize my overall...”.mp4",
    "open" : false,
    "display": false,
},
{
    "mittente": "Simona",
    "titolo": "Result of the test4",
    "emailHead": "Hey there!",
	"email": "Hey there! Thanks for coming over on such short notice.",
	"emailFooter": "Best wishes.",
    "videoPath": "media/Weeks/Week1/VideoRisposte/“When choosing to..”.mp4",
    "open" : false,
    "display": false,
},
{
    "mittente": "Simona",
    "titolo": "Welcome to the Week1",
    "emailHead": "Hey there!",
	"email": "Welcome to the first asynchronous session. During this week’s activities, you will engage in self-reflection about yourself, as an individual and as a consumer. After having completed a survey on personal scales in the TEST section; you will watch some videos requiring you to rate yourself on consumption patterns. When rating yourself, please remember that results will be kept confidential and won’t be shared with anyone. At the end of each item and scale on consumption behaviors, you will get a color on the screen, showing how you performed with respect to the mean of the scale. If you get a green screen, it means that you overperformed with respect to scale mean (your results are above the scale mean). If you get a yellow screen, it means that you scored exactly the scale mean. If you get a red screen, it means that you underperformed with respect to scale mean (your results are below the scale mean). Results could be helpful to understand areas of possible improvements (if any) in the direction of wiser consumption habits. Thank you for your attention, Enjoy this week’s activities!",
	"emailFooter": "Simona",
    "open" : false,
    "display": true,
    "order": 1
},
{
	"mittente": "Netflix",
    "titolo": "Abbiamo appena aggiunto un film che ti potrebbe piacere",
	"email": "Pimpi, piccolo grande eroe (Piglet's Big Movie) è un film del 2003 diretto da Francis Glebas. Terzo lungometraggio cinematografico d'animazione basato sui libri di Winnie the Pooh di A. A. Milne, il film ha come protagonista il personaggio di Pimpi che, vergognandosi di essere piccolo e goffo, si allontana nel Bosco dei Cento Acri, spingendo tutti i suoi amici a formare una squadra di ricerca per trovarlo. Pimpi, piccolo grande eroe fu prodotto dalla DisneyToon Studios e l'animazione fu realizzata principalmente dalla Walt Disney Animation Japan. Uscito negli Stati Uniti il 21 marzo 2003, il film fu recensito positivamente da buona parte della critica ma non fu un successo finanziario.",
    "open" : true,
    "display": true,
},
{
    "mittente": "JustDrink",
    "titolo": "Il tuo pranzo con 3€ di sconto? Ci pensiamo noi 🤑",
    "email": "Siamo quasi a metà giornata, ti meriti qualcosa di delizioso. Ordina un piatto fresco e appetitoso per la tua pausa pranzo da Poke House, McDonald's o prova tanti altri ristoranti. Usa il codice sconto di 3€* valido solo per pranzo che trovi qui sotto. Ordina il tuo pranzo con 3€ di sconto",
    "open" : true,
    "display": true,
},
{
    "mittente": "Payments",
    "titolo": "Ultima transazione, 23/05/22 alle 13:45 -",
    "email": "Ciao, la transazione è avvenuta con successo! \nImporto pre-autorizzato: €0,60\nPromo attiva:  nessuna\nAddebito: €0,60",
    "open" : true,
    "display": true,
},
{
    "mittente": "Indeeed",
    "titolo": "Segui Gli aggiornamenti dei tuoi contatti",
    "email": "Contenuti in evidenza nella tua rete\nMaticpind S.p.A.	Maticpind S.p.A.\n10.773 follower\nMaticpind è stata premiata all’Ascop Partners Day 2022, tenutosi il 25 maggio presso il Museo Nazionale... visualizza altro\n",
    "open" : true,
    "display": true,
},
{
    "mittente": "Payments",
    "titolo": "Ultima transazione, 23/05/22 alle 13:45 -",
    "email": "Ciao, la transazione è avvenuta con successo! \nImporto pre-autorizzato: €0,60\nPromo attiva:  nessuna\nAddebito: €0,60",
    "open" : true,
    "display": true,
},
{
    "mittente": "Indeeed",
    "titolo": "Segui Gli aggiornamenti dei tuoi contatti",
    "email": "Contenuti in evidenza nella tua rete\nMaticpind S.p.A.	Maticpind S.p.A.\n10.773 follower\nMaticpind è stata premiata all’Ascop Partners Day 2022, tenutosi il 25 maggio presso il Museo Nazionale... visualizza altro\n",
    "open" : true,
    "display": true,
}
];
