const EmailText = [
{
    "mittente": "Simona",
    "titolo": "Result of the test",
    "emailHead": "Hey there!",
	"email": "Hey there! Thanks for coming over on such short notice.",
	"emailFooter": "Best wishes.",
    "videoPath": "media/Weeks/Week1/VideoRisposte/“I throw food..”.mp4",
    "open" : false,
    "display": false,
},
{
    "mittente": "Simona",
    "titolo": "Result of the test",
    "emailHead": "Hey there!",
	"email": "Hey there! Thanks for coming over on such short notice.",
	"emailFooter": "Best wishes.",
    "videoPath": "media/Weeks/Week1/VideoRisposte/“When choosing to buy products, I often consider the sustainability of their production processes”.mp4",
    "open" : false,
    "display": false,
},
{
    "mittente": "Simona",
    "titolo": "Result of the test",
    "emailHead": "Hey there!",
	"email": "Hey there! Thanks for coming over on such short notice.",
	"emailFooter": "Best wishes.",
    "videoPath": "media/Weeks/Week1/VideoRisposte/“I minimize my overall...”.mp4",
    "open" : false,
    "display": false,
},
{
    "mittente": "Simona",
    "titolo": "Result of the test",
    "emailHead": "Hey there!",
	"email": "Hey there! Thanks for coming over on such short notice.",
	"emailFooter": "Best wishes.",
    "videoPath": "media/Weeks/Week1/VideoRisposte/“When choosing to..”.mp4",
    "open" : false,
    "display": false,
},
{
    "mittente": "Simona",
    "titolo": "Welcome to the Week1",
    "emailHead": "Hey there!",
	"email": "Welcome to the first asynchronous session. During this week’s activities, you will engage in self-reflection about yourself, as an individual and as a consumer. After having completed a survey on personal scales in the TEST section; you will watch some videos requiring you to rate yourself on consumption patterns. When rating yourself, please remember that results will be kept confidential and won’t be shared with anyone. At the end of each item and scale on consumption behaviors, you will get a color on the screen, showing how you performed with respect to the mean of the scale. If you get a green screen, it means that you overperformed with respect to scale mean (your results are above the scale mean). If you get a yellow screen, it means that you scored exactly the scale mean. If you get a red screen, it means that you underperformed with respect to scale mean (your results are below the scale mean). Results could be helpful to understand areas of possible improvements (if any) in the direction of wiser consumption habits. Thank you for your attention, Enjoy this week’s activities!",
	"emailFooter": "Simona",
    "open" : false,
    "display": true,
    "order": 1
},
{
	"mittente": "Neetflix",
    "titolo": "We just added a movie you might like",
	"email": "Piglet's Big Movie is a 2003 American animated musical comedy-drama film released by Walt Disney Pictures on March 21, 2003. The film features the characters from the Winnie-the-Pooh books written by A. A. Milne and is the third theatrically released Winnie the Pooh feature. In this film, Piglet is ashamed of being small and clumsy and wanders off into the Hundred Acre Wood, leading all of his friends to form a search party to find him. Piglet's Big Movie was produced by the Japanese office of Disneytoon Studios and the animation production was by Walt Disney Animation Japan, Inc. with additional animation provided by Gullwing Co., Ltd., additional background by Studio Fuga and digital ink and paint by T2 Studio.",
    "open" : true,
    "display": true,
},
{
    "mittente": "JustDrink",
    "titolo": "Your lunch with € 3 discount? We'll think about it 🤑",
    "email": "We're almost halfway through the day, you deserve something delicious. Order a fresh and mouthwatering dish for your lunch break at Poke House, McDonald's or try many other restaurants. Use the discount code of 3 € * valid only for lunch that you find below. Order your lunch with € 3 discount",
    "open" : true,
    "display": true,
},
{
    "mittente": "Payments",
    "titolo": "Last transaction, 23/05/22 alle 13:45 -",
    "email": "Hi, the transaction was successful! \ nPre-authorized amount: € 0.60 \ nActive promotion: none \ nCharge: € 0.60",
    "open" : true,
    "display": true,
},
{
    "mittente": "Indeeed",
    "titolo": "Follow the updates of your contacts",
    "email": "Your notice of job vacancies for Software Engineer 16 new job vacancies in Rome, Lazio, Italy match your preferences... See More\n",
    "open" : true,
    "display": true,
},
{
    "mittente": "Payments",
    "titolo": "Last transaction, 23/05/22 alle 13:45 -",
    "email": "Hi, the transaction was successful! \ nPre-authorized amount: € 0.60 \ nActive promotion: none \ nCharge: € 0.60",
    "open" : true,
    "display": true,
},
{
    "mittente": "Indeeed",
    "titolo": "Follow the updates of your contacts",
    "email": "Your notice of job vacancies for Sound Engineer 12 new job vacancies in Rome, Lazio, Italy match your preferences... See More\n",
    "open" : true,
    "display": true,
}
];
