const testSicuro = "https://impresaluiss.qualtrics.com/jfe/form/SV_e5p54KtjQhzUsZM";
const users = [
    {
      "Response Id": "",
      "Last Name": "VALARANO",
      "First Name": "BENIAMINO",
      "Contact Id": "CID_8qceJtg5EmiwAZ0",
      "Lookup Id": "CGC_Q8WjxTmS66bYNcc",
      "Transaction Id": "",
      "External Data Reference": "",
      "Email Address": "salvatore.musella@studenti.luiss.it",
      "Channel": "Email",
      "Status": "Email Not Sent",
      "Bounce Reason": "",
      "Sent to": "salvatore.musella@studenti.luiss.it",
      "Contact Frequency Rule Id": "",
      "Exceeded Contact Frequency": false,
      "End Date": "",
      "Link": "https://impresaluiss.qualtrics.com/jfe/form/SV_e5p54KtjQhzUsZM",
      "Link Expiration": "2022-11-15T14:01:15.046Z"
    },
    {
      "Response Id": "",
      "Last Name": "MUSELLA",
      "First Name": "SALVATORE",
      "Contact Id": "CID_8qceJtg5EmiwAZ0",
      "Lookup Id": "CGC_Q8WjxTmS66bYNcc",
      "Transaction Id": "",
      "External Data Reference": "",
      "Email Address": "salvatore.musella@studenti.luiss.it",
      "Channel": "Email",
      "Status": "Email Not Sent",
      "Bounce Reason": "",
      "Sent to": "salvatore.musella@studenti.luiss.it",
      "Contact Frequency Rule Id": "",
      "Exceeded Contact Frequency": false,
      "End Date": "",
      "Link": "https://impresaluiss.qualtrics.com/jfe/form/SV_1RjtGyao76w7Pn0?Q_CHL=gl&Q_DL=EMD_gJ4LqVM5YNtvWOH_1RjtGyao76w7Pn0_CGC_Q8WjxTmS66bYNcc&_g_=g",
      "Link Expiration": "2022-11-15T14:01:15.046Z"
    },
    {
      "Response Id": "",
      "Last Name": "GAZULLI",
      "First Name": "ANTONELA",
      "Contact Id": "CID_0OZKQn3J7Y3SO90",
      "Lookup Id": "CGC_A4YWZ4Gdk3K0mHz",
      "Transaction Id": "",
      "External Data Reference": "",
      "Email Address": "antonela.gazulli@studenti.luiss.it",
      "Channel": "Email",
      "Status": "Email Not Sent",
      "Bounce Reason": "",
      "Sent to": "antonela.gazulli@studenti.luiss.it",
      "Contact Frequency Rule Id": "",
      "Exceeded Contact Frequency": false,
      "End Date": "",
      "Link": "https://impresaluiss.qualtrics.com/jfe/form/SV_1RjtGyao76w7Pn0?Q_CHL=gl&Q_DL=EMD_VEWgjFuGn2P7uyc_1RjtGyao76w7Pn0_CGC_A4YWZ4Gdk3K0mHz&_g_=g",
      "Link Expiration": "2022-12-14T13:31:36.894Z"
    },
    {
      "Response Id": "",
      "Last Name": "NOBILE",
      "First Name": "CONCETTA",
      "Contact Id": "CID_0c5VSpj1bSSvqwC",
      "Lookup Id": "CGC_Vt6koLQregVZ4Nu",
      "Transaction Id": "",
      "External Data Reference": "",
      "Email Address": "concetta.nobile@studenti.luiss.it",
      "Channel": "Email",
      "Status": "Email Not Sent",
      "Bounce Reason": "",
      "Sent to": "concetta.nobile@studenti.luiss.it",
      "Contact Frequency Rule Id": "",
      "Exceeded Contact Frequency": false,
      "End Date": "",
      "Link": "https://impresaluiss.qualtrics.com/jfe/form/SV_1RjtGyao76w7Pn0?Q_CHL=gl&Q_DL=EMD_VEWgjFuGn2P7uyc_1RjtGyao76w7Pn0_CGC_Vt6koLQregVZ4Nu&_g_=g",
      "Link Expiration": "2022-12-14T13:31:36.894Z"
    },
    {
      "Response Id": "",
      "Last Name": "AGBOR",
      "First Name": "AKO ALLAN",
      "Contact Id": "CID_2iBEhmvCduq5DQa",
      "Lookup Id": "CGC_SvIiywgIz58So7n",
      "Transaction Id": "",
      "External Data Reference": "",
      "Email Address": "ako.agbor@studenti.luiss.it",
      "Channel": "Email",
      "Status": "Email Not Sent",
      "Bounce Reason": "",
      "Sent to": "ako.agbor@studenti.luiss.it",
      "Contact Frequency Rule Id": "",
      "Exceeded Contact Frequency": false,
      "End Date": "",
      "Link": "https://impresaluiss.qualtrics.com/jfe/form/SV_1RjtGyao76w7Pn0?Q_CHL=gl&Q_DL=EMD_VEWgjFuGn2P7uyc_1RjtGyao76w7Pn0_CGC_SvIiywgIz58So7n&_g_=g",
      "Link Expiration": "2022-12-14T13:31:36.894Z"
    },
    {
      "Response Id": "",
      "Last Name": "VU",
      "First Name": "THI QUYNH ANH",
      "Contact Id": "CID_39i7WB5EYMoE1Jc",
      "Lookup Id": "CGC_XZBk06P5EC9VP5n",
      "Transaction Id": "",
      "External Data Reference": "",
      "Email Address": "thi.vu@studenti.luiss.it",
      "Channel": "Email",
      "Status": "Email Not Sent",
      "Bounce Reason": "",
      "Sent to": "thi.vu@studenti.luiss.it",
      "Contact Frequency Rule Id": "",
      "Exceeded Contact Frequency": false,
      "End Date": "",
      "Link": "https://impresaluiss.qualtrics.com/jfe/form/SV_1RjtGyao76w7Pn0?Q_CHL=gl&Q_DL=EMD_VEWgjFuGn2P7uyc_1RjtGyao76w7Pn0_CGC_XZBk06P5EC9VP5n&_g_=g",
      "Link Expiration": "2022-12-14T13:31:36.894Z"
    },
    {
      "Response Id": "",
      "Last Name": "RUSSO",
      "First Name": "TERESA GAIA",
      "Contact Id": "CID_3I31IH6ON2xahxQ",
      "Lookup Id": "CGC_DMgyDuo43Kly3XL",
      "Transaction Id": "",
      "External Data Reference": "",
      "Email Address": "teresa.russo@alumni.luiss.it",
      "Channel": "Email",
      "Status": "Email Not Sent",
      "Bounce Reason": "",
      "Sent to": "teresa.russo@alumni.luiss.it",
      "Contact Frequency Rule Id": "",
      "Exceeded Contact Frequency": false,
      "End Date": "",
      "Link": "https://impresaluiss.qualtrics.com/jfe/form/SV_1RjtGyao76w7Pn0?Q_CHL=gl&Q_DL=EMD_VEWgjFuGn2P7uyc_1RjtGyao76w7Pn0_CGC_DMgyDuo43Kly3XL&_g_=g",
      "Link Expiration": "2022-12-14T13:31:36.894Z"
    },
    {
      "Response Id": "",
      "Last Name": "RAGUI",
      "First Name": "KHALID",
      "Contact Id": "CID_3IzBX8qJZF86OLs",
      "Lookup Id": "CGC_NRI076xMwguU78X",
      "Transaction Id": "",
      "External Data Reference": "",
      "Email Address": "khalid.ragui@studenti.luiss.it",
      "Channel": "Email",
      "Status": "Email Not Sent",
      "Bounce Reason": "",
      "Sent to": "khalid.ragui@studenti.luiss.it",
      "Contact Frequency Rule Id": "",
      "Exceeded Contact Frequency": false,
      "End Date": "",
      "Link": "https://impresaluiss.qualtrics.com/jfe/form/SV_1RjtGyao76w7Pn0?Q_CHL=gl&Q_DL=EMD_VEWgjFuGn2P7uyc_1RjtGyao76w7Pn0_CGC_NRI076xMwguU78X&_g_=g",
      "Link Expiration": "2022-12-14T13:31:36.894Z"
    },
    {
      "Response Id": "",
      "Last Name": "PISTOLESI",
      "First Name": "GIULIA",
      "Contact Id": "CID_3elazlMx1LPtAPA",
      "Lookup Id": "CGC_fqqMj0BzU3qmoem",
      "Transaction Id": "",
      "External Data Reference": "",
      "Email Address": "giulia.pistolesi@studenti.luiss.it",
      "Channel": "Email",
      "Status": "Email Not Sent",
      "Bounce Reason": "",
      "Sent to": "giulia.pistolesi@studenti.luiss.it",
      "Contact Frequency Rule Id": "",
      "Exceeded Contact Frequency": false,
      "End Date": "",
      "Link": "https://impresaluiss.qualtrics.com/jfe/form/SV_1RjtGyao76w7Pn0?Q_CHL=gl&Q_DL=EMD_VEWgjFuGn2P7uyc_1RjtGyao76w7Pn0_CGC_fqqMj0BzU3qmoem&_g_=g",
      "Link Expiration": "2022-12-14T13:31:36.894Z"
    },
    {
      "Response Id": "",
      "Last Name": "CASTIGLIONE",
      "First Name": "PAOLO",
      "Contact Id": "CID_3lRjOMWJvkkipL0",
      "Lookup Id": "CGC_pybsKPC4zQGCdbb",
      "Transaction Id": "",
      "External Data Reference": "",
      "Email Address": "paolo.castiglione@studenti.luiss.it",
      "Channel": "Email",
      "Status": "Email Not Sent",
      "Bounce Reason": "",
      "Sent to": "paolo.castiglione@studenti.luiss.it",
      "Contact Frequency Rule Id": "",
      "Exceeded Contact Frequency": false,
      "End Date": "",
      "Link": "https://impresaluiss.qualtrics.com/jfe/form/SV_1RjtGyao76w7Pn0?Q_CHL=gl&Q_DL=EMD_VEWgjFuGn2P7uyc_1RjtGyao76w7Pn0_CGC_pybsKPC4zQGCdbb&_g_=g",
      "Link Expiration": "2022-12-14T13:31:36.894Z"
    },
    {
      "Response Id": "",
      "Last Name": "CUTINI",
      "First Name": "AURORA",
      "Contact Id": "CID_3vX9hPbF6lGMrOK",
      "Lookup Id": "CGC_aYmZ9FhqQ1HdTev",
      "Transaction Id": "",
      "External Data Reference": "",
      "Email Address": "aurora.cutini@studenti.luiss.it",
      "Channel": "Email",
      "Status": "Email Not Sent",
      "Bounce Reason": "",
      "Sent to": "aurora.cutini@studenti.luiss.it",
      "Contact Frequency Rule Id": "",
      "Exceeded Contact Frequency": false,
      "End Date": "",
      "Link": "https://impresaluiss.qualtrics.com/jfe/form/SV_1RjtGyao76w7Pn0?Q_CHL=gl&Q_DL=EMD_VEWgjFuGn2P7uyc_1RjtGyao76w7Pn0_CGC_aYmZ9FhqQ1HdTev&_g_=g",
      "Link Expiration": "2022-12-14T13:31:36.894Z"
    },
    {
      "Response Id": "",
      "Last Name": "OSMANOVA",
      "First Name": "ALYONA",
      "Contact Id": "CID_42rL3C34WNu2ffE",
      "Lookup Id": "CGC_3bNwX5m8rFEZ6rD",
      "Transaction Id": "",
      "External Data Reference": "",
      "Email Address": "alyona.osmanova@studenti.luiss.it",
      "Channel": "Email",
      "Status": "Email Not Sent",
      "Bounce Reason": "",
      "Sent to": "alyona.osmanova@studenti.luiss.it",
      "Contact Frequency Rule Id": "",
      "Exceeded Contact Frequency": false,
      "End Date": "",
      "Link": "https://impresaluiss.qualtrics.com/jfe/form/SV_1RjtGyao76w7Pn0?Q_CHL=gl&Q_DL=EMD_VEWgjFuGn2P7uyc_1RjtGyao76w7Pn0_CGC_3bNwX5m8rFEZ6rD&_g_=g",
      "Link Expiration": "2022-12-14T13:31:36.894Z"
    },
    {
      "Response Id": "",
      "Last Name": "PETRUZZI",
      "First Name": "SARA",
      "Contact Id": "CID_4MxTtG02VkMAPfE",
      "Lookup Id": "CGC_x8d3ETlAlcQQ4l9",
      "Transaction Id": "",
      "External Data Reference": "",
      "Email Address": "sara.petruzzi@studenti.luiss.it",
      "Channel": "Email",
      "Status": "Email Not Sent",
      "Bounce Reason": "",
      "Sent to": "sara.petruzzi@studenti.luiss.it",
      "Contact Frequency Rule Id": "",
      "Exceeded Contact Frequency": false,
      "End Date": "",
      "Link": "https://impresaluiss.qualtrics.com/jfe/form/SV_1RjtGyao76w7Pn0?Q_CHL=gl&Q_DL=EMD_VEWgjFuGn2P7uyc_1RjtGyao76w7Pn0_CGC_x8d3ETlAlcQQ4l9&_g_=g",
      "Link Expiration": "2022-12-14T13:31:36.894Z"
    },
    {
      "Response Id": "",
      "Last Name": "RIZZO",
      "First Name": "GIORGIO",
      "Contact Id": "CID_4ZxFoMRFA9J1Cmy",
      "Lookup Id": "CGC_AUmS1IGNC1eZKDp",
      "Transaction Id": "",
      "External Data Reference": "",
      "Email Address": "giorgio.rizzo@studenti.luiss.it",
      "Channel": "Email",
      "Status": "Email Not Sent",
      "Bounce Reason": "",
      "Sent to": "giorgio.rizzo@studenti.luiss.it",
      "Contact Frequency Rule Id": "",
      "Exceeded Contact Frequency": false,
      "End Date": "",
      "Link": "https://impresaluiss.qualtrics.com/jfe/form/SV_1RjtGyao76w7Pn0?Q_CHL=gl&Q_DL=EMD_VEWgjFuGn2P7uyc_1RjtGyao76w7Pn0_CGC_AUmS1IGNC1eZKDp&_g_=g",
      "Link Expiration": "2022-12-14T13:31:36.894Z"
    },
    {
      "Response Id": "",
      "Last Name": "MAZZANTI",
      "First Name": "VALENTINA",
      "Contact Id": "CID_55QddgixMRz8Hfo",
      "Lookup Id": "CGC_uGuaD0xKeiduPZj",
      "Transaction Id": "",
      "External Data Reference": "",
      "Email Address": "valentina.mazzanti@studenti.luiss.it",
      "Channel": "Email",
      "Status": "Email Not Sent",
      "Bounce Reason": "",
      "Sent to": "valentina.mazzanti@studenti.luiss.it",
      "Contact Frequency Rule Id": "",
      "Exceeded Contact Frequency": false,
      "End Date": "",
      "Link": "https://impresaluiss.qualtrics.com/jfe/form/SV_1RjtGyao76w7Pn0?Q_CHL=gl&Q_DL=EMD_VEWgjFuGn2P7uyc_1RjtGyao76w7Pn0_CGC_uGuaD0xKeiduPZj&_g_=g",
      "Link Expiration": "2022-12-14T13:31:36.894Z"
    },
    {
      "Response Id": "",
      "Last Name": "D'ARPINO",
      "First Name": "ILARIA",
      "Contact Id": "CID_6S8BbCeGUzn68xU",
      "Lookup Id": "CGC_L3QspfxR0MLWMyj",
      "Transaction Id": "",
      "External Data Reference": "",
      "Email Address": "ilaria.darpino@studenti.luiss.it",
      "Channel": "Email",
      "Status": "Email Not Sent",
      "Bounce Reason": "",
      "Sent to": "ilaria.darpino@studenti.luiss.it",
      "Contact Frequency Rule Id": "",
      "Exceeded Contact Frequency": false,
      "End Date": "",
      "Link": "https://impresaluiss.qualtrics.com/jfe/form/SV_1RjtGyao76w7Pn0?Q_CHL=gl&Q_DL=EMD_VEWgjFuGn2P7uyc_1RjtGyao76w7Pn0_CGC_L3QspfxR0MLWMyj&_g_=g",
      "Link Expiration": "2022-12-14T13:31:36.894Z"
    },
    {
      "Response Id": "",
      "Last Name": "CUCCHIA",
      "First Name": "TAMARA",
      "Contact Id": "CID_7akMfjayl5SbFZA",
      "Lookup Id": "CGC_CPInsfDo4kkLgkx",
      "Transaction Id": "",
      "External Data Reference": "",
      "Email Address": "tamara.cucchia@studenti.luiss.it",
      "Channel": "Email",
      "Status": "Email Not Sent",
      "Bounce Reason": "",
      "Sent to": "tamara.cucchia@studenti.luiss.it",
      "Contact Frequency Rule Id": "",
      "Exceeded Contact Frequency": false,
      "End Date": "",
      "Link": "https://impresaluiss.qualtrics.com/jfe/form/SV_1RjtGyao76w7Pn0?Q_CHL=gl&Q_DL=EMD_VEWgjFuGn2P7uyc_1RjtGyao76w7Pn0_CGC_CPInsfDo4kkLgkx&_g_=g",
      "Link Expiration": "2022-12-14T13:31:36.894Z"
    },
    {
      "Response Id": "",
      "Last Name": "BALDONI",
      "First Name": "EMANUELE",
      "Contact Id": "CID_8FVrhaQctViIynY",
      "Lookup Id": "CGC_jlfZzwyrScEJct6",
      "Transaction Id": "",
      "External Data Reference": "",
      "Email Address": "emanuele-baldoni@studenti.luiss.it",
      "Channel": "Email",
      "Status": "Email Not Sent",
      "Bounce Reason": "",
      "Sent to": "emanuele-baldoni@studenti.luiss.it",
      "Contact Frequency Rule Id": "",
      "Exceeded Contact Frequency": false,
      "End Date": "",
      "Link": "https://impresaluiss.qualtrics.com/jfe/form/SV_1RjtGyao76w7Pn0?Q_CHL=gl&Q_DL=EMD_VEWgjFuGn2P7uyc_1RjtGyao76w7Pn0_CGC_jlfZzwyrScEJct6&_g_=g",
      "Link Expiration": "2022-12-14T13:31:36.894Z"
    },
    {
      "Response Id": "",
      "Last Name": "MAINARDI",
      "First Name": "CATERINA",
      "Contact Id": "CID_8HctH3AETyIRPjU",
      "Lookup Id": "CGC_ZLHZcuquuoNT3Aw",
      "Transaction Id": "",
      "External Data Reference": "",
      "Email Address": "",
      "Channel": "Email",
      "Status": "Email Not Sent",
      "Bounce Reason": "",
      "Sent to": "",
      "Contact Frequency Rule Id": "",
      "Exceeded Contact Frequency": false,
      "End Date": "",
      "Link": "https://impresaluiss.qualtrics.com/jfe/form/SV_1RjtGyao76w7Pn0?Q_CHL=gl&Q_DL=EMD_VEWgjFuGn2P7uyc_1RjtGyao76w7Pn0_CGC_ZLHZcuquuoNT3Aw&_g_=g",
      "Link Expiration": "2022-12-14T13:31:36.894Z"
    },
    {
      "Response Id": "",
      "Last Name": "AZAM",
      "First Name": "MAIRA",
      "Contact Id": "CID_8q9FUhPvgpfiPvE",
      "Lookup Id": "CGC_ifvdvLE7dRe92mJ",
      "Transaction Id": "",
      "External Data Reference": "",
      "Email Address": "maira.azam@studenti.luiss.it",
      "Channel": "Email",
      "Status": "Email Not Sent",
      "Bounce Reason": "",
      "Sent to": "maira.azam@studenti.luiss.it",
      "Contact Frequency Rule Id": "",
      "Exceeded Contact Frequency": false,
      "End Date": "",
      "Link": "https://impresaluiss.qualtrics.com/jfe/form/SV_1RjtGyao76w7Pn0?Q_CHL=gl&Q_DL=EMD_VEWgjFuGn2P7uyc_1RjtGyao76w7Pn0_CGC_ifvdvLE7dRe92mJ&_g_=g",
      "Link Expiration": "2022-12-14T13:31:36.894Z"
    },
    {
      "Response Id": "",
      "Last Name": "WASSERMANN",
      "First Name": "LEA",
      "Contact Id": "CID_9SUAxL5MAdNHesu",
      "Lookup Id": "CGC_TplD4QUsxWdtPX1",
      "Transaction Id": "",
      "External Data Reference": "",
      "Email Address": "lea.wassermann@studenti.luiss.it",
      "Channel": "Email",
      "Status": "Email Not Sent",
      "Bounce Reason": "",
      "Sent to": "lea.wassermann@studenti.luiss.it",
      "Contact Frequency Rule Id": "",
      "Exceeded Contact Frequency": false,
      "End Date": "",
      "Link": "https://impresaluiss.qualtrics.com/jfe/form/SV_1RjtGyao76w7Pn0?Q_CHL=gl&Q_DL=EMD_VEWgjFuGn2P7uyc_1RjtGyao76w7Pn0_CGC_TplD4QUsxWdtPX1&_g_=g",
      "Link Expiration": "2022-12-14T13:31:36.894Z"
    },
    {
      "Response Id": "",
      "Last Name": "DI BUGNO",
      "First Name": "GIULIA",
      "Contact Id": "CID_9ZiYDeeuKlv8GVM",
      "Lookup Id": "CGC_Bs30SGMPLZL6CXl",
      "Transaction Id": "",
      "External Data Reference": "",
      "Email Address": "giulia.dibugno@studenti.luiss.it",
      "Channel": "Email",
      "Status": "Email Not Sent",
      "Bounce Reason": "",
      "Sent to": "giulia.dibugno@studenti.luiss.it",
      "Contact Frequency Rule Id": "",
      "Exceeded Contact Frequency": false,
      "End Date": "",
      "Link": "https://impresaluiss.qualtrics.com/jfe/form/SV_1RjtGyao76w7Pn0?Q_CHL=gl&Q_DL=EMD_VEWgjFuGn2P7uyc_1RjtGyao76w7Pn0_CGC_Bs30SGMPLZL6CXl&_g_=g",
      "Link Expiration": "2022-12-14T13:31:36.894Z"
    },
    {
      "Response Id": "",
      "Last Name": "IADEMARCO",
      "First Name": "ROBERTO",
      "Contact Id": "CID_9yu350D5hUVCwvk",
      "Lookup Id": "CGC_ZqoMh53Rztw9HpH",
      "Transaction Id": "",
      "External Data Reference": "",
      "Email Address": "roberto.iademarco@studenti.luiss.it",
      "Channel": "Email",
      "Status": "Email Not Sent",
      "Bounce Reason": "",
      "Sent to": "roberto.iademarco@studenti.luiss.it",
      "Contact Frequency Rule Id": "",
      "Exceeded Contact Frequency": false,
      "End Date": "",
      "Link": "https://impresaluiss.qualtrics.com/jfe/form/SV_1RjtGyao76w7Pn0?Q_CHL=gl&Q_DL=EMD_VEWgjFuGn2P7uyc_1RjtGyao76w7Pn0_CGC_ZqoMh53Rztw9HpH&_g_=g",
      "Link Expiration": "2022-12-14T13:31:36.894Z"
    },
    {
      "Response Id": "",
      "Last Name": "SOKHIBOVA",
      "First Name": "FOTIMA",
      "Contact Id": "CID_bIB6mxr3rtUuGyy",
      "Lookup Id": "CGC_WrK5tzwnCwaFzqN",
      "Transaction Id": "",
      "External Data Reference": "",
      "Email Address": "fotima.sokhibova@studenti.luiss.it",
      "Channel": "Email",
      "Status": "Email Not Sent",
      "Bounce Reason": "",
      "Sent to": "fotima.sokhibova@studenti.luiss.it",
      "Contact Frequency Rule Id": "",
      "Exceeded Contact Frequency": false,
      "End Date": "",
      "Link": "https://impresaluiss.qualtrics.com/jfe/form/SV_1RjtGyao76w7Pn0?Q_CHL=gl&Q_DL=EMD_VEWgjFuGn2P7uyc_1RjtGyao76w7Pn0_CGC_WrK5tzwnCwaFzqN&_g_=g",
      "Link Expiration": "2022-12-14T13:31:36.894Z"
    },
    {
      "Response Id": "",
      "Last Name": "DE LUCA",
      "First Name": "ANGELICA",
      "Contact Id": "CID_bQ3AVAnZNQZgwOa",
      "Lookup Id": "CGC_KIbtqYwLmPqng8S",
      "Transaction Id": "",
      "External Data Reference": "",
      "Email Address": "angelica.deluca@studenti.luiss.it",
      "Channel": "Email",
      "Status": "Email Not Sent",
      "Bounce Reason": "",
      "Sent to": "angelica.deluca@studenti.luiss.it",
      "Contact Frequency Rule Id": "",
      "Exceeded Contact Frequency": false,
      "End Date": "",
      "Link": "https://impresaluiss.qualtrics.com/jfe/form/SV_1RjtGyao76w7Pn0?Q_CHL=gl&Q_DL=EMD_VEWgjFuGn2P7uyc_1RjtGyao76w7Pn0_CGC_KIbtqYwLmPqng8S&_g_=g",
      "Link Expiration": "2022-12-14T13:31:36.894Z"
    },
    {
      "Response Id": "",
      "Last Name": "MANCINO",
      "First Name": "ANTONIO",
      "Contact Id": "CID_eG6IoVl39wnwWcS",
      "Lookup Id": "CGC_qtVU537btWqbwaY",
      "Transaction Id": "",
      "External Data Reference": "",
      "Email Address": "antonio.mancino0107@studenti.luiss.it",
      "Channel": "Email",
      "Status": "Email Not Sent",
      "Bounce Reason": "",
      "Sent to": "antonio.mancino0107@studenti.luiss.it",
      "Contact Frequency Rule Id": "",
      "Exceeded Contact Frequency": false,
      "End Date": "",
      "Link": "https://impresaluiss.qualtrics.com/jfe/form/SV_1RjtGyao76w7Pn0?Q_CHL=gl&Q_DL=EMD_VEWgjFuGn2P7uyc_1RjtGyao76w7Pn0_CGC_qtVU537btWqbwaY&_g_=g",
      "Link Expiration": "2022-12-14T13:31:36.894Z"
    },
    {
      "Response Id": "",
      "Last Name": "KYCYKU",
      "First Name": "POLIKSENI",
      "Contact Id": "CID_eMcT3FM8eq0fi4K",
      "Lookup Id": "CGC_fXGmL9FrXkzpAUc",
      "Transaction Id": "",
      "External Data Reference": "",
      "Email Address": "polikseni.kycyku@studenti.luiss.it",
      "Channel": "Email",
      "Status": "Email Not Sent",
      "Bounce Reason": "",
      "Sent to": "polikseni.kycyku@studenti.luiss.it",
      "Contact Frequency Rule Id": "",
      "Exceeded Contact Frequency": false,
      "End Date": "",
      "Link": "https://impresaluiss.qualtrics.com/jfe/form/SV_1RjtGyao76w7Pn0?Q_CHL=gl&Q_DL=EMD_VEWgjFuGn2P7uyc_1RjtGyao76w7Pn0_CGC_fXGmL9FrXkzpAUc&_g_=g",
      "Link Expiration": "2022-12-14T13:31:36.894Z"
    },
    {
      "Response Id": "",
      "Last Name": "UBA",
      "First Name": "EBERE JOSEPHINE",
      "Contact Id": "CID_ezgKWW32ZPpQTDo",
      "Lookup Id": "CGC_A0NwlIUDUT6mVMM",
      "Transaction Id": "",
      "External Data Reference": "",
      "Email Address": "ebere.uba@studenti.luiss.it",
      "Channel": "Email",
      "Status": "Email Not Sent",
      "Bounce Reason": "",
      "Sent to": "ebere.uba@studenti.luiss.it",
      "Contact Frequency Rule Id": "",
      "Exceeded Contact Frequency": false,
      "End Date": "",
      "Link": "https://impresaluiss.qualtrics.com/jfe/form/SV_1RjtGyao76w7Pn0?Q_CHL=gl&Q_DL=EMD_VEWgjFuGn2P7uyc_1RjtGyao76w7Pn0_CGC_A0NwlIUDUT6mVMM&_g_=g",
      "Link Expiration": "2022-12-14T13:31:36.894Z"
    }
  ]