const users = [
    {
      "Response Id": "",
      "Contact Id": "CID_eG6IoVl39wnwWcS",
      "Link": "https://impresaluiss.qualtrics.com/jfe/form/SV_bDyhXqppXl7sWRU?Q_CHL=gl&Q_DL=YacmjbzuYnxUFwP_bDyhXqppXl7sWRU_CGC_qtVU537btWqbwaY",
      "Exceeded Contact Frequency": false,
      "Link Expiration": "2022-12-14T16:51:46.743Z",
      "Status": "Email Not Sent",
      "Last Name": "MANCINO",
      "First Name": "ANTONIO",
      "External Data Reference": "",
      "Email": "antonio.mancino0107@studenti.luiss.it",
      "Unsubscribed": false
    },
    {
      "Response Id": "",
      "Contact Id": "CID_4MxTtG02VkMAPfE",
      "Link": "https://impresaluiss.qualtrics.com/jfe/form/SV_bDyhXqppXl7sWRU?Q_CHL=gl&Q_DL=YacmjbzuYnxUFwP_bDyhXqppXl7sWRU_CGC_x8d3ETlAlcQQ4l9",
      "Exceeded Contact Frequency": false,
      "Link Expiration": "2022-12-14T16:51:46.743Z",
      "Status": "Email Not Sent",
      "Last Name": "PETRUZZI",
      "First Name": "SARA",
      "External Data Reference": "",
      "Email": "sara.petruzzi@studenti.luiss.it",
      "Unsubscribed": false
    },
    {
      "Response Id": "",
      "Contact Id": "CID_42rL3C34WNu2ffE",
      "Link": "https://impresaluiss.qualtrics.com/jfe/form/SV_bDyhXqppXl7sWRU?Q_CHL=gl&Q_DL=YacmjbzuYnxUFwP_bDyhXqppXl7sWRU_CGC_3bNwX5m8rFEZ6rD",
      "Exceeded Contact Frequency": false,
      "Link Expiration": "2022-12-14T16:51:46.743Z",
      "Status": "Email Not Sent",
      "Last Name": "OSMANOVA",
      "First Name": "ALYONA",
      "External Data Reference": "",
      "Email": "alyona.osmanova@studenti.luiss.it",
      "Unsubscribed": false
    },
    {
      "Response Id": "",
      "Contact Id": "CID_8q9FUhPvgpfiPvE",
      "Link": "https://impresaluiss.qualtrics.com/jfe/form/SV_bDyhXqppXl7sWRU?Q_CHL=gl&Q_DL=YacmjbzuYnxUFwP_bDyhXqppXl7sWRU_CGC_ifvdvLE7dRe92mJ",
      "Exceeded Contact Frequency": false,
      "Link Expiration": "2022-12-14T16:51:46.743Z",
      "Status": "Email Not Sent",
      "Last Name": "AZAM",
      "First Name": "MAIRA",
      "External Data Reference": "",
      "Email": "maira.azam@studenti.luiss.it",
      "Unsubscribed": false
    },
    {
      "Response Id": "",
      "Contact Id": "CID_55QddgixMRz8Hfo",
      "Link": "https://impresaluiss.qualtrics.com/jfe/form/SV_bDyhXqppXl7sWRU?Q_CHL=gl&Q_DL=YacmjbzuYnxUFwP_bDyhXqppXl7sWRU_CGC_uGuaD0xKeiduPZj",
      "Exceeded Contact Frequency": false,
      "Link Expiration": "2022-12-14T16:51:46.743Z",
      "Status": "Email Not Sent",
      "Last Name": "MAZZANTI",
      "First Name": "VALENTINA",
      "External Data Reference": "",
      "Email": "valentina.mazzanti@studenti.luiss.it",
      "Unsubscribed": false
    },
    {
      "Response Id": "",
      "Contact Id": "CID_eMcT3FM8eq0fi4K",
      "Link": "https://impresaluiss.qualtrics.com/jfe/form/SV_bDyhXqppXl7sWRU?Q_CHL=gl&Q_DL=YacmjbzuYnxUFwP_bDyhXqppXl7sWRU_CGC_fXGmL9FrXkzpAUc",
      "Exceeded Contact Frequency": false,
      "Link Expiration": "2022-12-14T16:51:46.743Z",
      "Status": "Email Not Sent",
      "Last Name": "KYCYKU",
      "First Name": "POLIKSENI",
      "External Data Reference": "",
      "Email": "polikseni.kycyku@studenti.luiss.it",
      "Unsubscribed": false
    },
    {
      "Response Id": "",
      "Contact Id": "CID_3elazlMx1LPtAPA",
      "Link": "https://impresaluiss.qualtrics.com/jfe/form/SV_bDyhXqppXl7sWRU?Q_CHL=gl&Q_DL=YacmjbzuYnxUFwP_bDyhXqppXl7sWRU_CGC_fqqMj0BzU3qmoem",
      "Exceeded Contact Frequency": false,
      "Link Expiration": "2022-12-14T16:51:46.743Z",
      "Status": "Email Not Sent",
      "Last Name": "PISTOLESI",
      "First Name": "GIULIA",
      "External Data Reference": "",
      "Email": "giulia.pistolesi@studenti.luiss.it",
      "Unsubscribed": false
    },
    {
      "Response Id": "",
      "Contact Id": "CID_bQ3AVAnZNQZgwOa",
      "Link": "https://impresaluiss.qualtrics.com/jfe/form/SV_bDyhXqppXl7sWRU?Q_CHL=gl&Q_DL=YacmjbzuYnxUFwP_bDyhXqppXl7sWRU_CGC_KIbtqYwLmPqng8S",
      "Exceeded Contact Frequency": false,
      "Link Expiration": "2022-12-14T16:51:46.743Z",
      "Status": "Email Not Sent",
      "Last Name": "DE LUCA",
      "First Name": "ANGELICA",
      "External Data Reference": "",
      "Email": "angelica.deluca@studenti.luiss.it",
      "Unsubscribed": false
    },
    {
      "Response Id": "",
      "Contact Id": "CID_3I31IH6ON2xahxQ",
      "Link": "https://impresaluiss.qualtrics.com/jfe/form/SV_bDyhXqppXl7sWRU?Q_CHL=gl&Q_DL=YacmjbzuYnxUFwP_bDyhXqppXl7sWRU_CGC_DMgyDuo43Kly3XL",
      "Exceeded Contact Frequency": false,
      "Link Expiration": "2022-12-14T16:51:46.743Z",
      "Status": "Email Not Sent",
      "Last Name": "RUSSO",
      "First Name": "TERESA GAIA",
      "External Data Reference": "",
      "Email": "teresa.russo@alumni.luiss.it",
      "Unsubscribed": false
    },
    {
      "Response Id": "",
      "Contact Id": "CID_9ZiYDeeuKlv8GVM",
      "Link": "https://impresaluiss.qualtrics.com/jfe/form/SV_bDyhXqppXl7sWRU?Q_CHL=gl&Q_DL=YacmjbzuYnxUFwP_bDyhXqppXl7sWRU_CGC_Bs30SGMPLZL6CXl",
      "Exceeded Contact Frequency": false,
      "Link Expiration": "2022-12-14T16:51:46.743Z",
      "Status": "Email Not Sent",
      "Last Name": "DI BUGNO",
      "First Name": "GIULIA",
      "External Data Reference": "",
      "Email": "giulia.dibugno@studenti.luiss.it",
      "Unsubscribed": false
    },
    {
      "Response Id": "",
      "Contact Id": "CID_6S8BbCeGUzn68xU",
      "Link": "https://impresaluiss.qualtrics.com/jfe/form/SV_bDyhXqppXl7sWRU?Q_CHL=gl&Q_DL=YacmjbzuYnxUFwP_bDyhXqppXl7sWRU_CGC_L3QspfxR0MLWMyj",
      "Exceeded Contact Frequency": false,
      "Link Expiration": "2022-12-14T16:51:46.743Z",
      "Status": "Email Not Sent",
      "Last Name": "D'ARPINO",
      "First Name": "ILARIA",
      "External Data Reference": "",
      "Email": "ilaria.darpino@studenti.luiss.it",
      "Unsubscribed": false
    },
    {
      "Response Id": "",
      "Contact Id": "CID_ezgKWW32ZPpQTDo",
      "Link": "https://impresaluiss.qualtrics.com/jfe/form/SV_bDyhXqppXl7sWRU?Q_CHL=gl&Q_DL=YacmjbzuYnxUFwP_bDyhXqppXl7sWRU_CGC_A0NwlIUDUT6mVMM",
      "Exceeded Contact Frequency": false,
      "Link Expiration": "2022-12-14T16:51:46.743Z",
      "Status": "Email Not Sent",
      "Last Name": "UBA",
      "First Name": "EBERE JOSEPHINE",
      "External Data Reference": "",
      "Email": "ebere.uba@studenti.luiss.it",
      "Unsubscribed": false
    },
    {
      "Response Id": "",
      "Contact Id": "CID_3vX9hPbF6lGMrOK",
      "Link": "https://impresaluiss.qualtrics.com/jfe/form/SV_bDyhXqppXl7sWRU?Q_CHL=gl&Q_DL=YacmjbzuYnxUFwP_bDyhXqppXl7sWRU_CGC_aYmZ9FhqQ1HdTev",
      "Exceeded Contact Frequency": false,
      "Link Expiration": "2022-12-14T16:51:46.743Z",
      "Status": "Email Not Sent",
      "Last Name": "CUTINI",
      "First Name": "AURORA",
      "External Data Reference": "",
      "Email": "aurora.cutini@studenti.luiss.it",
      "Unsubscribed": false
    },
    {
      "Response Id": "",
      "Contact Id": "CID_8FVrhaQctViIynY",
      "Link": "https://impresaluiss.qualtrics.com/jfe/form/SV_bDyhXqppXl7sWRU?Q_CHL=gl&Q_DL=YacmjbzuYnxUFwP_bDyhXqppXl7sWRU_CGC_jlfZzwyrScEJct6",
      "Exceeded Contact Frequency": false,
      "Link Expiration": "2022-12-14T16:51:46.743Z",
      "Status": "Email Not Sent",
      "Last Name": "BALDONI",
      "First Name": "EMANUELE",
      "External Data Reference": "",
      "Email": "emanuele-baldoni@studenti.luiss.it",
      "Unsubscribed": false
    },
    {
      "Response Id": "",
      "Contact Id": "CID_0OZKQn3J7Y3SO90",
      "Link": "https://impresaluiss.qualtrics.com/jfe/form/SV_bDyhXqppXl7sWRU?Q_CHL=gl&Q_DL=YacmjbzuYnxUFwP_bDyhXqppXl7sWRU_CGC_A4YWZ4Gdk3K0mHz",
      "Exceeded Contact Frequency": false,
      "Link Expiration": "2022-12-14T16:51:46.743Z",
      "Status": "Email Not Sent",
      "Last Name": "GAZULLI",
      "First Name": "ANTONELA",
      "External Data Reference": "",
      "Email": "antonela.gazulli@studenti.luiss.it",
      "Unsubscribed": false
    },
    {
      "Response Id": "",
      "Contact Id": "CID_7akMfjayl5SbFZA",
      "Link": "https://impresaluiss.qualtrics.com/jfe/form/SV_bDyhXqppXl7sWRU?Q_CHL=gl&Q_DL=YacmjbzuYnxUFwP_bDyhXqppXl7sWRU_CGC_CPInsfDo4kkLgkx",
      "Exceeded Contact Frequency": false,
      "Link Expiration": "2022-12-14T16:51:46.743Z",
      "Status": "Email Not Sent",
      "Last Name": "CUCCHIA",
      "First Name": "TAMARA",
      "External Data Reference": "",
      "Email": "tamara.cucchia@studenti.luiss.it",
      "Unsubscribed": false
    },
    {
      "Response Id": "",
      "Contact Id": "CID_39i7WB5EYMoE1Jc",
      "Link": "https://impresaluiss.qualtrics.com/jfe/form/SV_bDyhXqppXl7sWRU?Q_CHL=gl&Q_DL=YacmjbzuYnxUFwP_bDyhXqppXl7sWRU_CGC_XZBk06P5EC9VP5n",
      "Exceeded Contact Frequency": false,
      "Link Expiration": "2022-12-14T16:51:46.743Z",
      "Status": "Email Not Sent",
      "Last Name": "VU",
      "First Name": "THI QUYNH ANH",
      "External Data Reference": "",
      "Email": "thi.vu@studenti.luiss.it",
      "Unsubscribed": false
    },
    {
      "Response Id": "",
      "Contact Id": "CID_3IzBX8qJZF86OLs",
      "Link": "https://impresaluiss.qualtrics.com/jfe/form/SV_bDyhXqppXl7sWRU?Q_CHL=gl&Q_DL=YacmjbzuYnxUFwP_bDyhXqppXl7sWRU_CGC_NRI076xMwguU78X",
      "Exceeded Contact Frequency": false,
      "Link Expiration": "2022-12-14T16:51:46.743Z",
      "Status": "Email Not Sent",
      "Last Name": "RAGUI",
      "First Name": "KHALID",
      "External Data Reference": "",
      "Email": "khalid.ragui@studenti.luiss.it",
      "Unsubscribed": false
    },
    {
      "Response Id": "",
      "Contact Id": "CID_9SUAxL5MAdNHesu",
      "Link": "https://impresaluiss.qualtrics.com/jfe/form/SV_bDyhXqppXl7sWRU?Q_CHL=gl&Q_DL=YacmjbzuYnxUFwP_bDyhXqppXl7sWRU_CGC_TplD4QUsxWdtPX1",
      "Exceeded Contact Frequency": false,
      "Link Expiration": "2022-12-14T16:51:46.743Z",
      "Status": "Email Not Sent",
      "Last Name": "WASSERMANN",
      "First Name": "LEA",
      "External Data Reference": "",
      "Email": "lea.wassermann@studenti.luiss.it",
      "Unsubscribed": false
    },
    {
      "Response Id": "",
      "Contact Id": "CID_0c5VSpj1bSSvqwC",
      "Link": "https://impresaluiss.qualtrics.com/jfe/form/SV_bDyhXqppXl7sWRU?Q_CHL=gl&Q_DL=YacmjbzuYnxUFwP_bDyhXqppXl7sWRU_CGC_Vt6koLQregVZ4Nu",
      "Exceeded Contact Frequency": false,
      "Link Expiration": "2022-12-14T16:51:46.743Z",
      "Status": "Email Not Sent",
      "Last Name": "NOBILE",
      "First Name": "CONCETTA",
      "External Data Reference": "",
      "Email": "concetta.nobile@studenti.luiss.it",
      "Unsubscribed": false
    },
    {
      "Response Id": "",
      "Contact Id": "CID_4ZxFoMRFA9J1Cmy",
      "Link": "https://impresaluiss.qualtrics.com/jfe/form/SV_bDyhXqppXl7sWRU?Q_CHL=gl&Q_DL=YacmjbzuYnxUFwP_bDyhXqppXl7sWRU_CGC_AUmS1IGNC1eZKDp",
      "Exceeded Contact Frequency": false,
      "Link Expiration": "2022-12-14T16:51:46.743Z",
      "Status": "Email Not Sent",
      "Last Name": "RIZZO",
      "First Name": "GIORGIO",
      "External Data Reference": "",
      "Email": "giorgio.rizzo@studenti.luiss.it",
      "Unsubscribed": false
    },
    {
      "Response Id": "",
      "Contact Id": "CID_bIB6mxr3rtUuGyy",
      "Link": "https://impresaluiss.qualtrics.com/jfe/form/SV_bDyhXqppXl7sWRU?Q_CHL=gl&Q_DL=YacmjbzuYnxUFwP_bDyhXqppXl7sWRU_CGC_WrK5tzwnCwaFzqN",
      "Exceeded Contact Frequency": false,
      "Link Expiration": "2022-12-14T16:51:46.743Z",
      "Status": "Email Not Sent",
      "Last Name": "SOKHIBOVA",
      "First Name": "FOTIMA",
      "External Data Reference": "",
      "Email": "fotima.sokhibova@studenti.luiss.it",
      "Unsubscribed": false
    },
    {
      "Response Id": "",
      "Contact Id": "CID_3lRjOMWJvkkipL0",
      "Link": "https://impresaluiss.qualtrics.com/jfe/form/SV_bDyhXqppXl7sWRU?Q_CHL=gl&Q_DL=YacmjbzuYnxUFwP_bDyhXqppXl7sWRU_CGC_pybsKPC4zQGCdbb",
      "Exceeded Contact Frequency": false,
      "Link Expiration": "2022-12-14T16:51:46.743Z",
      "Status": "Email Not Sent",
      "Last Name": "CASTIGLIONE",
      "First Name": "PAOLO",
      "External Data Reference": "",
      "Email": "paolo.castiglione@studenti.luiss.it",
      "Unsubscribed": false
    },
    {
      "Response Id": "",
      "Contact Id": "CID_2iBEhmvCduq5DQa",
      "Link": "https://impresaluiss.qualtrics.com/jfe/form/SV_bDyhXqppXl7sWRU?Q_CHL=gl&Q_DL=YacmjbzuYnxUFwP_bDyhXqppXl7sWRU_CGC_SvIiywgIz58So7n",
      "Exceeded Contact Frequency": false,
      "Link Expiration": "2022-12-14T16:51:46.743Z",
      "Status": "Email Not Sent",
      "Last Name": "AGBOR",
      "First Name": "AKO ALLAN",
      "External Data Reference": "",
      "Email": "ako.agbor@studenti.luiss.it",
      "Unsubscribed": false
    },
    {
      "Response Id": "",
      "Contact Id": "CID_8HctH3AETyIRPjU",
      "Link": "https://impresaluiss.qualtrics.com/jfe/form/SV_bDyhXqppXl7sWRU?Q_CHL=gl&Q_DL=YacmjbzuYnxUFwP_bDyhXqppXl7sWRU_CGC_ZLHZcuquuoNT3Aw",
      "Exceeded Contact Frequency": false,
      "Link Expiration": "2022-12-14T16:51:46.743Z",
      "Status": "Email Not Sent",
      "Last Name": "MAINARDI",
      "First Name": "CATERINA",
      "External Data Reference": "",
      "Email": "",
      "Unsubscribed": false
    },
    {
      "Response Id": "",
      "Contact Id": "CID_9yu350D5hUVCwvk",
      "Link": "https://impresaluiss.qualtrics.com/jfe/form/SV_bDyhXqppXl7sWRU?Q_CHL=gl&Q_DL=YacmjbzuYnxUFwP_bDyhXqppXl7sWRU_CGC_ZqoMh53Rztw9HpH",
      "Exceeded Contact Frequency": false,
      "Link Expiration": "2022-12-14T16:51:46.743Z",
      "Status": "Email Not Sent",
      "Last Name": "IADEMARCO",
      "First Name": "ROBERTO",
      "External Data Reference": "",
      "Email": "roberto.iademarco@studenti.luiss.it",
      "Unsubscribed": false
    }
  ]