const testSicuro = "https://impresaluiss.qualtrics.com/jfe/form/SV_42bnyhDnxWUW3ci";
const testSicuro2 = "https://impresaluiss.qualtrics.com/jfe/form/SV_6G83KOMZyBs5B2K";
const users = [
    {
      "Response Id": "",
      "Contact Id": "CID_9Y5UKYuIhrVJR1s",
      "Link": "https://impresaluiss.qualtrics.com/jfe/form/SV_559mIuEpTh7NBDo?Q_CHL=gl&Q_DL=m7JdkxK6Plq8766_559mIuEpTh7NBDo_CGC_DZIdw5RtD9dX8FH",
      "Exceeded Contact Frequency": false,
      "Link Expiration": "2022-12-15T17:08:22.788Z",
      "Status": "Email Not Sent",
      "Last Name": "RUSSO",
      "First Name": "TERESA GAIA",
      "External Data Reference": "",
      "Email": "teresa.russo@alumni.luiss.it",
      "Unsubscribed": false
    },
    {
      "Response Id": "",
      "Contact Id": "CID_0BrMb4jL9h7FOUm",
      "Link": "https://impresaluiss.qualtrics.com/jfe/form/SV_559mIuEpTh7NBDo?Q_CHL=gl&Q_DL=m7JdkxK6Plq8766_559mIuEpTh7NBDo_CGC_y0dciRibmHpSzai",
      "Exceeded Contact Frequency": false,
      "Link Expiration": "2022-12-15T17:08:22.788Z",
      "Status": "Email Not Sent",
      "Last Name": "CASTIGLIONE",
      "First Name": "PAOLO",
      "External Data Reference": "",
      "Email": "paolo.castiglione@studenti.luiss.it",
      "Unsubscribed": false
    },
    {
      "Response Id": "",
      "Contact Id": "CID_9AHBVcEwHNIkfWK",
      "Link": "https://impresaluiss.qualtrics.com/jfe/form/SV_559mIuEpTh7NBDo?Q_CHL=gl&Q_DL=m7JdkxK6Plq8766_559mIuEpTh7NBDo_CGC_Vyqdtedf02oEeUv",
      "Exceeded Contact Frequency": false,
      "Link Expiration": "2022-12-15T17:08:22.788Z",
      "Status": "Email Not Sent",
      "Last Name": "CUTINI",
      "First Name": "AURORA",
      "External Data Reference": "",
      "Email": "aurora.cutini@studenti.luiss.it",
      "Unsubscribed": false
    },
    {
      "Response Id": "",
      "Contact Id": "CID_6lgQvGHNEkPpNJA",
      "Link": "https://impresaluiss.qualtrics.com/jfe/form/SV_559mIuEpTh7NBDo?Q_CHL=gl&Q_DL=m7JdkxK6Plq8766_559mIuEpTh7NBDo_CGC_oVtZfiYEET5KuvJ",
      "Exceeded Contact Frequency": false,
      "Link Expiration": "2022-12-15T17:08:22.788Z",
      "Status": "Email Not Sent",
      "Last Name": "RIZZO",
      "First Name": "GIORGIO",
      "External Data Reference": "",
      "Email": "giorgio.rizzo@studenti.luiss.it",
      "Unsubscribed": false
    },
    {
      "Response Id": "",
      "Contact Id": "CID_3slcCwXmBuHdPUi",
      "Link": "https://impresaluiss.qualtrics.com/jfe/form/SV_559mIuEpTh7NBDo?Q_CHL=gl&Q_DL=m7JdkxK6Plq8766_559mIuEpTh7NBDo_CGC_wVMAX99kDR7tm3s",
      "Exceeded Contact Frequency": false,
      "Link Expiration": "2022-12-15T17:08:22.788Z",
      "Status": "Email Not Sent",
      "Last Name": "MAINARDI",
      "First Name": "CATERINA",
      "External Data Reference": "",
      "Email": "",
      "Unsubscribed": false
    },
    {
      "Response Id": "",
      "Contact Id": "CID_eqW9tKt71SnHcF0",
      "Link": "https://impresaluiss.qualtrics.com/jfe/form/SV_559mIuEpTh7NBDo?Q_CHL=gl&Q_DL=m7JdkxK6Plq8766_559mIuEpTh7NBDo_CGC_iIR0a0miWaX02ZW",
      "Exceeded Contact Frequency": false,
      "Link Expiration": "2022-12-15T17:08:22.788Z",
      "Status": "Email Not Sent",
      "Last Name": "GAZULLI",
      "First Name": "ANTONELA",
      "External Data Reference": "",
      "Email": "antonela.gazulli@studenti.luiss.it",
      "Unsubscribed": false
    },
    {
      "Response Id": "",
      "Contact Id": "CID_3EhR5NOYxF8HJC6",
      "Link": "https://impresaluiss.qualtrics.com/jfe/form/SV_559mIuEpTh7NBDo?Q_CHL=gl&Q_DL=m7JdkxK6Plq8766_559mIuEpTh7NBDo_CGC_k6sXBDM2a6GQJfg",
      "Exceeded Contact Frequency": false,
      "Link Expiration": "2022-12-15T17:08:22.788Z",
      "Status": "Email Not Sent",
      "Last Name": "OSMANOVA",
      "First Name": "ALYONA",
      "External Data Reference": "",
      "Email": "alyona.osmanova@studenti.luiss.it",
      "Unsubscribed": false
    },
    {
      "Response Id": "",
      "Contact Id": "CID_cD8GKZ2JmqcwNZI",
      "Link": "https://impresaluiss.qualtrics.com/jfe/form/SV_559mIuEpTh7NBDo?Q_CHL=gl&Q_DL=m7JdkxK6Plq8766_559mIuEpTh7NBDo_CGC_OBhvvszN9eQn0p8",
      "Exceeded Contact Frequency": false,
      "Link Expiration": "2022-12-15T17:08:22.788Z",
      "Status": "Email Not Sent",
      "Last Name": "AZAM",
      "First Name": "MAIRA",
      "External Data Reference": "",
      "Email": "maira.azam@studenti.luiss.it",
      "Unsubscribed": false
    },
    {
      "Response Id": "",
      "Contact Id": "CID_2aaW6n9eQGX9WBM",
      "Link": "https://impresaluiss.qualtrics.com/jfe/form/SV_559mIuEpTh7NBDo?Q_CHL=gl&Q_DL=m7JdkxK6Plq8766_559mIuEpTh7NBDo_CGC_BRsuheJaIWJPxKe",
      "Exceeded Contact Frequency": false,
      "Link Expiration": "2022-12-15T17:08:22.788Z",
      "Status": "Email Not Sent",
      "Last Name": "UBA",
      "First Name": "EBERE JOSEPHINE",
      "External Data Reference": "",
      "Email": "ebere.uba@studenti.luiss.it",
      "Unsubscribed": false
    },
    {
      "Response Id": "",
      "Contact Id": "CID_aeKyNtx4g8DEJ5s",
      "Link": "https://impresaluiss.qualtrics.com/jfe/form/SV_559mIuEpTh7NBDo?Q_CHL=gl&Q_DL=m7JdkxK6Plq8766_559mIuEpTh7NBDo_CGC_ODmeu1yyEyag7B8",
      "Exceeded Contact Frequency": false,
      "Link Expiration": "2022-12-15T17:08:22.788Z",
      "Status": "Email Not Sent",
      "Last Name": "DE LUCA",
      "First Name": "ANGELICA",
      "External Data Reference": "",
      "Email": "angelica.deluca@studenti.luiss.it",
      "Unsubscribed": false
    },
    {
      "Response Id": "",
      "Contact Id": "CID_be0rxk0y3RC5VwW",
      "Link": "https://impresaluiss.qualtrics.com/jfe/form/SV_559mIuEpTh7NBDo?Q_CHL=gl&Q_DL=m7JdkxK6Plq8766_559mIuEpTh7NBDo_CGC_JQtZ0t1CQC90kG8",
      "Exceeded Contact Frequency": false,
      "Link Expiration": "2022-12-15T17:08:22.788Z",
      "Status": "Email Not Sent",
      "Last Name": "RAGUI",
      "First Name": "KHALID",
      "External Data Reference": "",
      "Email": "khalid.ragui@studenti.luiss.it",
      "Unsubscribed": false
    },
    {
      "Response Id": "",
      "Contact Id": "CID_00Vbav15atuv03Q",
      "Link": "https://impresaluiss.qualtrics.com/jfe/form/SV_559mIuEpTh7NBDo?Q_CHL=gl&Q_DL=m7JdkxK6Plq8766_559mIuEpTh7NBDo_CGC_Nv7EPYXEHz5oTgv",
      "Exceeded Contact Frequency": false,
      "Link Expiration": "2022-12-15T17:08:22.788Z",
      "Status": "Email Not Sent",
      "Last Name": "NOBILE",
      "First Name": "CONCETTA",
      "External Data Reference": "",
      "Email": "concetta.nobile@studenti.luiss.it",
      "Unsubscribed": false
    },
    {
      "Response Id": "",
      "Contact Id": "CID_42XrqJglPT6WsfQ",
      "Link": "https://impresaluiss.qualtrics.com/jfe/form/SV_559mIuEpTh7NBDo?Q_CHL=gl&Q_DL=m7JdkxK6Plq8766_559mIuEpTh7NBDo_CGC_72coA62jVnrOwIg",
      "Exceeded Contact Frequency": false,
      "Link Expiration": "2022-12-15T17:08:22.788Z",
      "Status": "Email Not Sent",
      "Last Name": "AGBOR",
      "First Name": "AKO ALLAN",
      "External Data Reference": "",
      "Email": "ako.agbor@studenti.luiss.it",
      "Unsubscribed": false
    },
    {
      "Response Id": "",
      "Contact Id": "CID_em6QYBEuTCWc1Nk",
      "Link": "https://impresaluiss.qualtrics.com/jfe/form/SV_559mIuEpTh7NBDo?Q_CHL=gl&Q_DL=m7JdkxK6Plq8766_559mIuEpTh7NBDo_CGC_T8wUygfAAyfIub7",
      "Exceeded Contact Frequency": false,
      "Link Expiration": "2022-12-15T17:08:22.788Z",
      "Status": "Email Not Sent",
      "Last Name": "KYCYKU",
      "First Name": "POLIKSENI",
      "External Data Reference": "",
      "Email": "polikseni.kycyku@studenti.luiss.it",
      "Unsubscribed": false
    },
    {
      "Response Id": "",
      "Contact Id": "CID_e8nMif1uC6sOGzA",
      "Link": "https://impresaluiss.qualtrics.com/jfe/form/SV_559mIuEpTh7NBDo?Q_CHL=gl&Q_DL=m7JdkxK6Plq8766_559mIuEpTh7NBDo_CGC_492EUzboMh37HnL",
      "Exceeded Contact Frequency": false,
      "Link Expiration": "2022-12-15T17:08:22.788Z",
      "Status": "Email Not Sent",
      "Last Name": "DI BUGNO",
      "First Name": "GIULIA",
      "External Data Reference": "",
      "Email": "giulia.dibugno@studenti.luiss.it",
      "Unsubscribed": false
    },
    {
      "Response Id": "",
      "Contact Id": "CID_egl2GTSwQg4pyWG",
      "Link": "https://impresaluiss.qualtrics.com/jfe/form/SV_559mIuEpTh7NBDo?Q_CHL=gl&Q_DL=m7JdkxK6Plq8766_559mIuEpTh7NBDo_CGC_0PB89jDBXjKXI15",
      "Exceeded Contact Frequency": false,
      "Link Expiration": "2022-12-15T17:08:22.788Z",
      "Status": "Email Not Sent",
      "Last Name": "SOKHIBOVA",
      "First Name": "FOTIMA",
      "External Data Reference": "",
      "Email": "fotima.sokhibova@studenti.luiss.it",
      "Unsubscribed": false
    },
    {
      "Response Id": "",
      "Contact Id": "CID_9Two1sBDCDjt6Ie",
      "Link": "https://impresaluiss.qualtrics.com/jfe/form/SV_559mIuEpTh7NBDo?Q_CHL=gl&Q_DL=m7JdkxK6Plq8766_559mIuEpTh7NBDo_CGC_XdaJ1w6cAWmmzYU",
      "Exceeded Contact Frequency": false,
      "Link Expiration": "2022-12-15T17:08:22.788Z",
      "Status": "Email Not Sent",
      "Last Name": "BALDONI",
      "First Name": "EMANUELE",
      "External Data Reference": "",
      "Email": "emanuele-baldoni@studenti.luiss.it",
      "Unsubscribed": false
    },
    {
      "Response Id": "",
      "Contact Id": "CID_8zRmyWKFhGR1uRw",
      "Link": "https://impresaluiss.qualtrics.com/jfe/form/SV_559mIuEpTh7NBDo?Q_CHL=gl&Q_DL=m7JdkxK6Plq8766_559mIuEpTh7NBDo_CGC_dz0Uv680hfVEFgu",
      "Exceeded Contact Frequency": false,
      "Link Expiration": "2022-12-15T17:08:22.788Z",
      "Status": "Email Not Sent",
      "Last Name": "CUCCHIA",
      "First Name": "TAMARA",
      "External Data Reference": "",
      "Email": "tamara.cucchia@studenti.luiss.it",
      "Unsubscribed": false
    },
    {
      "Response Id": "",
      "Contact Id": "CID_cSa7czcoLpQYJHo",
      "Link": "https://impresaluiss.qualtrics.com/jfe/form/SV_559mIuEpTh7NBDo?Q_CHL=gl&Q_DL=m7JdkxK6Plq8766_559mIuEpTh7NBDo_CGC_QBCtwOGtt5v7Pm4",
      "Exceeded Contact Frequency": false,
      "Link Expiration": "2022-12-15T17:08:22.788Z",
      "Status": "Email Not Sent",
      "Last Name": "MANCINO",
      "First Name": "ANTONIO",
      "External Data Reference": "",
      "Email": "antonio.mancino0107@studenti.luiss.it",
      "Unsubscribed": false
    },
    {
      "Response Id": "",
      "Contact Id": "CID_1AgdsRTBRinVtrg",
      "Link": "https://impresaluiss.qualtrics.com/jfe/form/SV_559mIuEpTh7NBDo?Q_CHL=gl&Q_DL=m7JdkxK6Plq8766_559mIuEpTh7NBDo_CGC_Mpz2PleEZ7VRS7Q",
      "Exceeded Contact Frequency": false,
      "Link Expiration": "2022-12-15T17:08:22.788Z",
      "Status": "Email Not Sent",
      "Last Name": "MAZZANTI",
      "First Name": "VALENTINA",
      "External Data Reference": "",
      "Email": "valentina.mazzanti@studenti.luiss.it",
      "Unsubscribed": false
    },
    {
      "Response Id": "",
      "Contact Id": "CID_3OaeSD98MIo1F2u",
      "Link": "https://impresaluiss.qualtrics.com/jfe/form/SV_559mIuEpTh7NBDo?Q_CHL=gl&Q_DL=m7JdkxK6Plq8766_559mIuEpTh7NBDo_CGC_dAUbeBEkzesl4Jt",
      "Exceeded Contact Frequency": false,
      "Link Expiration": "2022-12-15T17:08:22.788Z",
      "Status": "Email Not Sent",
      "Last Name": "PETRUZZI",
      "First Name": "SARA",
      "External Data Reference": "",
      "Email": "sara.petruzzi@studenti.luiss.it",
      "Unsubscribed": false
    },
    {
      "Response Id": "",
      "Contact Id": "CID_5ouVApek8vVq5Gm",
      "Link": "https://impresaluiss.qualtrics.com/jfe/form/SV_559mIuEpTh7NBDo?Q_CHL=gl&Q_DL=m7JdkxK6Plq8766_559mIuEpTh7NBDo_CGC_0XulvY3g3PzOi0r",
      "Exceeded Contact Frequency": false,
      "Link Expiration": "2022-12-15T17:08:22.788Z",
      "Status": "Email Not Sent",
      "Last Name": "MUSELLA",
      "First Name": "SALVATORE",
      "External Data Reference": "",
      "Email": "salvatore.musella@studenti.luiss.it",
      "Unsubscribed": false
    },
    {
      "Response Id": "",
      "Contact Id": "CID_8BM5GQfUfRXhYcm",
      "Link": "https://impresaluiss.qualtrics.com/jfe/form/SV_559mIuEpTh7NBDo?Q_CHL=gl&Q_DL=m7JdkxK6Plq8766_559mIuEpTh7NBDo_CGC_BfWVOaYKFdoWnGb",
      "Exceeded Contact Frequency": false,
      "Link Expiration": "2022-12-15T17:08:22.788Z",
      "Status": "Email Not Sent",
      "Last Name": "VU",
      "First Name": "THI QUYNH ANH",
      "External Data Reference": "",
      "Email": "thi.vu@studenti.luiss.it",
      "Unsubscribed": false
    },
    {
      "Response Id": "",
      "Contact Id": "CID_aeEaRbooo9DYHS6",
      "Link": "https://impresaluiss.qualtrics.com/jfe/form/SV_559mIuEpTh7NBDo?Q_CHL=gl&Q_DL=m7JdkxK6Plq8766_559mIuEpTh7NBDo_CGC_DI828aofSGSlt8h",
      "Exceeded Contact Frequency": false,
      "Link Expiration": "2022-12-15T17:08:22.788Z",
      "Status": "Email Not Sent",
      "Last Name": "PISTOLESI",
      "First Name": "GIULIA",
      "External Data Reference": "",
      "Email": "giulia.pistolesi@studenti.luiss.it",
      "Unsubscribed": false
    },
    {
      "Response Id": "",
      "Contact Id": "CID_9S3aOzE3lsndenA",
      "Link": "https://impresaluiss.qualtrics.com/jfe/form/SV_559mIuEpTh7NBDo?Q_CHL=gl&Q_DL=m7JdkxK6Plq8766_559mIuEpTh7NBDo_CGC_yy35QWgrTI1UkRj",
      "Exceeded Contact Frequency": false,
      "Link Expiration": "2022-12-15T17:08:22.788Z",
      "Status": "Email Not Sent",
      "Last Name": "WASSERMANN",
      "First Name": "LEA",
      "External Data Reference": "",
      "Email": "lea.wassermann@studenti.luiss.it",
      "Unsubscribed": false
    },
    {
      "Response Id": "",
      "Contact Id": "CID_eLHGXpHJpPLEtb8",
      "Link": "https://impresaluiss.qualtrics.com/jfe/form/SV_559mIuEpTh7NBDo?Q_CHL=gl&Q_DL=m7JdkxK6Plq8766_559mIuEpTh7NBDo_CGC_aVyoIaLyfIRBVef",
      "Exceeded Contact Frequency": false,
      "Link Expiration": "2022-12-15T17:08:22.788Z",
      "Status": "Email Not Sent",
      "Last Name": "IADEMARCO",
      "First Name": "ROBERTO",
      "External Data Reference": "",
      "Email": "roberto.iademarco@studenti.luiss.it",
      "Unsubscribed": false
    },
    {
      "Response Id": "",
      "Contact Id": "CID_6XKYiThw0vNI2dU",
      "Link": "https://impresaluiss.qualtrics.com/jfe/form/SV_559mIuEpTh7NBDo?Q_CHL=gl&Q_DL=m7JdkxK6Plq8766_559mIuEpTh7NBDo_CGC_DyGwaHJ0rYBSDhB",
      "Exceeded Contact Frequency": false,
      "Link Expiration": "2022-12-15T17:08:22.788Z",
      "Status": "Email Not Sent",
      "Last Name": "D'ARPINO",
      "First Name": "ILARIA",
      "External Data Reference": "",
      "Email": "ilaria.darpino@studenti.luiss.it",
      "Unsubscribed": false
    }
  ] 
const users2 = [
    {
      "Response Id": "",
      "Contact Id": "CID_9Y5UKYuIhrVJR1s",
      "Link": "https://impresaluiss.qualtrics.com/jfe/form/SV_eScjs14ptWfE1Jc?Q_CHL=gl&Q_DL=WMyUUgKWyQwt6v0_eScjs14ptWfE1Jc_CGC_DZIdw5RtD9dX8FH",
      "Exceeded Contact Frequency": false,
      "Link Expiration": "2022-12-15T17:08:58.535Z",
      "Status": "Email Not Sent",
      "Last Name": "RUSSO",
      "First Name": "TERESA GAIA",
      "External Data Reference": "",
      "Email": "teresa.russo@alumni.luiss.it",
      "Unsubscribed": false
    },
    {
      "Response Id": "",
      "Contact Id": "CID_0BrMb4jL9h7FOUm",
      "Link": "https://impresaluiss.qualtrics.com/jfe/form/SV_eScjs14ptWfE1Jc?Q_CHL=gl&Q_DL=WMyUUgKWyQwt6v0_eScjs14ptWfE1Jc_CGC_y0dciRibmHpSzai",
      "Exceeded Contact Frequency": false,
      "Link Expiration": "2022-12-15T17:08:58.535Z",
      "Status": "Email Not Sent",
      "Last Name": "CASTIGLIONE",
      "First Name": "PAOLO",
      "External Data Reference": "",
      "Email": "paolo.castiglione@studenti.luiss.it",
      "Unsubscribed": false
    },
    {
      "Response Id": "",
      "Contact Id": "CID_9AHBVcEwHNIkfWK",
      "Link": "https://impresaluiss.qualtrics.com/jfe/form/SV_eScjs14ptWfE1Jc?Q_CHL=gl&Q_DL=WMyUUgKWyQwt6v0_eScjs14ptWfE1Jc_CGC_Vyqdtedf02oEeUv",
      "Exceeded Contact Frequency": false,
      "Link Expiration": "2022-12-15T17:08:58.535Z",
      "Status": "Email Not Sent",
      "Last Name": "CUTINI",
      "First Name": "AURORA",
      "External Data Reference": "",
      "Email": "aurora.cutini@studenti.luiss.it",
      "Unsubscribed": false
    },
    {
      "Response Id": "",
      "Contact Id": "CID_6lgQvGHNEkPpNJA",
      "Link": "https://impresaluiss.qualtrics.com/jfe/form/SV_eScjs14ptWfE1Jc?Q_CHL=gl&Q_DL=WMyUUgKWyQwt6v0_eScjs14ptWfE1Jc_CGC_oVtZfiYEET5KuvJ",
      "Exceeded Contact Frequency": false,
      "Link Expiration": "2022-12-15T17:08:58.535Z",
      "Status": "Email Not Sent",
      "Last Name": "RIZZO",
      "First Name": "GIORGIO",
      "External Data Reference": "",
      "Email": "giorgio.rizzo@studenti.luiss.it",
      "Unsubscribed": false
    },
    {
      "Response Id": "",
      "Contact Id": "CID_3slcCwXmBuHdPUi",
      "Link": "https://impresaluiss.qualtrics.com/jfe/form/SV_eScjs14ptWfE1Jc?Q_CHL=gl&Q_DL=WMyUUgKWyQwt6v0_eScjs14ptWfE1Jc_CGC_wVMAX99kDR7tm3s",
      "Exceeded Contact Frequency": false,
      "Link Expiration": "2022-12-15T17:08:58.535Z",
      "Status": "Email Not Sent",
      "Last Name": "MAINARDI",
      "First Name": "CATERINA",
      "External Data Reference": "",
      "Email": "",
      "Unsubscribed": false
    },
    {
      "Response Id": "",
      "Contact Id": "CID_eqW9tKt71SnHcF0",
      "Link": "https://impresaluiss.qualtrics.com/jfe/form/SV_eScjs14ptWfE1Jc?Q_CHL=gl&Q_DL=WMyUUgKWyQwt6v0_eScjs14ptWfE1Jc_CGC_iIR0a0miWaX02ZW",
      "Exceeded Contact Frequency": false,
      "Link Expiration": "2022-12-15T17:08:58.535Z",
      "Status": "Email Not Sent",
      "Last Name": "GAZULLI",
      "First Name": "ANTONELA",
      "External Data Reference": "",
      "Email": "antonela.gazulli@studenti.luiss.it",
      "Unsubscribed": false
    },
    {
      "Response Id": "",
      "Contact Id": "CID_3EhR5NOYxF8HJC6",
      "Link": "https://impresaluiss.qualtrics.com/jfe/form/SV_eScjs14ptWfE1Jc?Q_CHL=gl&Q_DL=WMyUUgKWyQwt6v0_eScjs14ptWfE1Jc_CGC_k6sXBDM2a6GQJfg",
      "Exceeded Contact Frequency": false,
      "Link Expiration": "2022-12-15T17:08:58.535Z",
      "Status": "Email Not Sent",
      "Last Name": "OSMANOVA",
      "First Name": "ALYONA",
      "External Data Reference": "",
      "Email": "alyona.osmanova@studenti.luiss.it",
      "Unsubscribed": false
    },
    {
      "Response Id": "",
      "Contact Id": "CID_cD8GKZ2JmqcwNZI",
      "Link": "https://impresaluiss.qualtrics.com/jfe/form/SV_eScjs14ptWfE1Jc?Q_CHL=gl&Q_DL=WMyUUgKWyQwt6v0_eScjs14ptWfE1Jc_CGC_OBhvvszN9eQn0p8",
      "Exceeded Contact Frequency": false,
      "Link Expiration": "2022-12-15T17:08:58.535Z",
      "Status": "Email Not Sent",
      "Last Name": "AZAM",
      "First Name": "MAIRA",
      "External Data Reference": "",
      "Email": "maira.azam@studenti.luiss.it",
      "Unsubscribed": false
    },
    {
      "Response Id": "",
      "Contact Id": "CID_2aaW6n9eQGX9WBM",
      "Link": "https://impresaluiss.qualtrics.com/jfe/form/SV_eScjs14ptWfE1Jc?Q_CHL=gl&Q_DL=WMyUUgKWyQwt6v0_eScjs14ptWfE1Jc_CGC_BRsuheJaIWJPxKe",
      "Exceeded Contact Frequency": false,
      "Link Expiration": "2022-12-15T17:08:58.535Z",
      "Status": "Email Not Sent",
      "Last Name": "UBA",
      "First Name": "EBERE JOSEPHINE",
      "External Data Reference": "",
      "Email": "ebere.uba@studenti.luiss.it",
      "Unsubscribed": false
    },
    {
      "Response Id": "",
      "Contact Id": "CID_aeKyNtx4g8DEJ5s",
      "Link": "https://impresaluiss.qualtrics.com/jfe/form/SV_eScjs14ptWfE1Jc?Q_CHL=gl&Q_DL=WMyUUgKWyQwt6v0_eScjs14ptWfE1Jc_CGC_ODmeu1yyEyag7B8",
      "Exceeded Contact Frequency": false,
      "Link Expiration": "2022-12-15T17:08:58.535Z",
      "Status": "Email Not Sent",
      "Last Name": "DE LUCA",
      "First Name": "ANGELICA",
      "External Data Reference": "",
      "Email": "angelica.deluca@studenti.luiss.it",
      "Unsubscribed": false
    },
    {
      "Response Id": "",
      "Contact Id": "CID_be0rxk0y3RC5VwW",
      "Link": "https://impresaluiss.qualtrics.com/jfe/form/SV_eScjs14ptWfE1Jc?Q_CHL=gl&Q_DL=WMyUUgKWyQwt6v0_eScjs14ptWfE1Jc_CGC_JQtZ0t1CQC90kG8",
      "Exceeded Contact Frequency": false,
      "Link Expiration": "2022-12-15T17:08:58.535Z",
      "Status": "Email Not Sent",
      "Last Name": "RAGUI",
      "First Name": "KHALID",
      "External Data Reference": "",
      "Email": "khalid.ragui@studenti.luiss.it",
      "Unsubscribed": false
    },
    {
      "Response Id": "",
      "Contact Id": "CID_00Vbav15atuv03Q",
      "Link": "https://impresaluiss.qualtrics.com/jfe/form/SV_eScjs14ptWfE1Jc?Q_CHL=gl&Q_DL=WMyUUgKWyQwt6v0_eScjs14ptWfE1Jc_CGC_Nv7EPYXEHz5oTgv",
      "Exceeded Contact Frequency": false,
      "Link Expiration": "2022-12-15T17:08:58.535Z",
      "Status": "Email Not Sent",
      "Last Name": "NOBILE",
      "First Name": "CONCETTA",
      "External Data Reference": "",
      "Email": "concetta.nobile@studenti.luiss.it",
      "Unsubscribed": false
    },
    {
      "Response Id": "",
      "Contact Id": "CID_42XrqJglPT6WsfQ",
      "Link": "https://impresaluiss.qualtrics.com/jfe/form/SV_eScjs14ptWfE1Jc?Q_CHL=gl&Q_DL=WMyUUgKWyQwt6v0_eScjs14ptWfE1Jc_CGC_72coA62jVnrOwIg",
      "Exceeded Contact Frequency": false,
      "Link Expiration": "2022-12-15T17:08:58.535Z",
      "Status": "Email Not Sent",
      "Last Name": "AGBOR",
      "First Name": "AKO ALLAN",
      "External Data Reference": "",
      "Email": "ako.agbor@studenti.luiss.it",
      "Unsubscribed": false
    },
    {
      "Response Id": "",
      "Contact Id": "CID_em6QYBEuTCWc1Nk",
      "Link": "https://impresaluiss.qualtrics.com/jfe/form/SV_eScjs14ptWfE1Jc?Q_CHL=gl&Q_DL=WMyUUgKWyQwt6v0_eScjs14ptWfE1Jc_CGC_T8wUygfAAyfIub7",
      "Exceeded Contact Frequency": false,
      "Link Expiration": "2022-12-15T17:08:58.535Z",
      "Status": "Email Not Sent",
      "Last Name": "KYCYKU",
      "First Name": "POLIKSENI",
      "External Data Reference": "",
      "Email": "polikseni.kycyku@studenti.luiss.it",
      "Unsubscribed": false
    },
    {
      "Response Id": "",
      "Contact Id": "CID_e8nMif1uC6sOGzA",
      "Link": "https://impresaluiss.qualtrics.com/jfe/form/SV_eScjs14ptWfE1Jc?Q_CHL=gl&Q_DL=WMyUUgKWyQwt6v0_eScjs14ptWfE1Jc_CGC_492EUzboMh37HnL",
      "Exceeded Contact Frequency": false,
      "Link Expiration": "2022-12-15T17:08:58.535Z",
      "Status": "Email Not Sent",
      "Last Name": "DI BUGNO",
      "First Name": "GIULIA",
      "External Data Reference": "",
      "Email": "giulia.dibugno@studenti.luiss.it",
      "Unsubscribed": false
    },
    {
      "Response Id": "",
      "Contact Id": "CID_egl2GTSwQg4pyWG",
      "Link": "https://impresaluiss.qualtrics.com/jfe/form/SV_eScjs14ptWfE1Jc?Q_CHL=gl&Q_DL=WMyUUgKWyQwt6v0_eScjs14ptWfE1Jc_CGC_0PB89jDBXjKXI15",
      "Exceeded Contact Frequency": false,
      "Link Expiration": "2022-12-15T17:08:58.535Z",
      "Status": "Email Not Sent",
      "Last Name": "SOKHIBOVA",
      "First Name": "FOTIMA",
      "External Data Reference": "",
      "Email": "fotima.sokhibova@studenti.luiss.it",
      "Unsubscribed": false
    },
    {
      "Response Id": "",
      "Contact Id": "CID_9Two1sBDCDjt6Ie",
      "Link": "https://impresaluiss.qualtrics.com/jfe/form/SV_eScjs14ptWfE1Jc?Q_CHL=gl&Q_DL=WMyUUgKWyQwt6v0_eScjs14ptWfE1Jc_CGC_XdaJ1w6cAWmmzYU",
      "Exceeded Contact Frequency": false,
      "Link Expiration": "2022-12-15T17:08:58.535Z",
      "Status": "Email Not Sent",
      "Last Name": "BALDONI",
      "First Name": "EMANUELE",
      "External Data Reference": "",
      "Email": "emanuele-baldoni@studenti.luiss.it",
      "Unsubscribed": false
    },
    {
      "Response Id": "",
      "Contact Id": "CID_8zRmyWKFhGR1uRw",
      "Link": "https://impresaluiss.qualtrics.com/jfe/form/SV_eScjs14ptWfE1Jc?Q_CHL=gl&Q_DL=WMyUUgKWyQwt6v0_eScjs14ptWfE1Jc_CGC_dz0Uv680hfVEFgu",
      "Exceeded Contact Frequency": false,
      "Link Expiration": "2022-12-15T17:08:58.535Z",
      "Status": "Email Not Sent",
      "Last Name": "CUCCHIA",
      "First Name": "TAMARA",
      "External Data Reference": "",
      "Email": "tamara.cucchia@studenti.luiss.it",
      "Unsubscribed": false
    },
    {
      "Response Id": "",
      "Contact Id": "CID_cSa7czcoLpQYJHo",
      "Link": "https://impresaluiss.qualtrics.com/jfe/form/SV_eScjs14ptWfE1Jc?Q_CHL=gl&Q_DL=WMyUUgKWyQwt6v0_eScjs14ptWfE1Jc_CGC_QBCtwOGtt5v7Pm4",
      "Exceeded Contact Frequency": false,
      "Link Expiration": "2022-12-15T17:08:58.535Z",
      "Status": "Email Not Sent",
      "Last Name": "MANCINO",
      "First Name": "ANTONIO",
      "External Data Reference": "",
      "Email": "antonio.mancino0107@studenti.luiss.it",
      "Unsubscribed": false
    },
    {
      "Response Id": "",
      "Contact Id": "CID_1AgdsRTBRinVtrg",
      "Link": "https://impresaluiss.qualtrics.com/jfe/form/SV_eScjs14ptWfE1Jc?Q_CHL=gl&Q_DL=WMyUUgKWyQwt6v0_eScjs14ptWfE1Jc_CGC_Mpz2PleEZ7VRS7Q",
      "Exceeded Contact Frequency": false,
      "Link Expiration": "2022-12-15T17:08:58.535Z",
      "Status": "Email Not Sent",
      "Last Name": "MAZZANTI",
      "First Name": "VALENTINA",
      "External Data Reference": "",
      "Email": "valentina.mazzanti@studenti.luiss.it",
      "Unsubscribed": false
    },
    {
      "Response Id": "",
      "Contact Id": "CID_3OaeSD98MIo1F2u",
      "Link": "https://impresaluiss.qualtrics.com/jfe/form/SV_eScjs14ptWfE1Jc?Q_CHL=gl&Q_DL=WMyUUgKWyQwt6v0_eScjs14ptWfE1Jc_CGC_dAUbeBEkzesl4Jt",
      "Exceeded Contact Frequency": false,
      "Link Expiration": "2022-12-15T17:08:58.535Z",
      "Status": "Email Not Sent",
      "Last Name": "PETRUZZI",
      "First Name": "SARA",
      "External Data Reference": "",
      "Email": "sara.petruzzi@studenti.luiss.it",
      "Unsubscribed": false
    },
    {
      "Response Id": "",
      "Contact Id": "CID_5ouVApek8vVq5Gm",
      "Link": "https://impresaluiss.qualtrics.com/jfe/form/SV_eScjs14ptWfE1Jc?Q_CHL=gl&Q_DL=WMyUUgKWyQwt6v0_eScjs14ptWfE1Jc_CGC_0XulvY3g3PzOi0r",
      "Exceeded Contact Frequency": false,
      "Link Expiration": "2022-12-15T17:08:58.535Z",
      "Status": "Email Not Sent",
      "Last Name": "MUSELLA",
      "First Name": "SALVATORE",
      "External Data Reference": "",
      "Email": "salvatore.musella@studenti.luiss.it",
      "Unsubscribed": false
    },
    {
      "Response Id": "",
      "Contact Id": "CID_8BM5GQfUfRXhYcm",
      "Link": "https://impresaluiss.qualtrics.com/jfe/form/SV_eScjs14ptWfE1Jc?Q_CHL=gl&Q_DL=WMyUUgKWyQwt6v0_eScjs14ptWfE1Jc_CGC_BfWVOaYKFdoWnGb",
      "Exceeded Contact Frequency": false,
      "Link Expiration": "2022-12-15T17:08:58.535Z",
      "Status": "Email Not Sent",
      "Last Name": "VU",
      "First Name": "THI QUYNH ANH",
      "External Data Reference": "",
      "Email": "thi.vu@studenti.luiss.it",
      "Unsubscribed": false
    },
    {
      "Response Id": "",
      "Contact Id": "CID_aeEaRbooo9DYHS6",
      "Link": "https://impresaluiss.qualtrics.com/jfe/form/SV_eScjs14ptWfE1Jc?Q_CHL=gl&Q_DL=WMyUUgKWyQwt6v0_eScjs14ptWfE1Jc_CGC_DI828aofSGSlt8h",
      "Exceeded Contact Frequency": false,
      "Link Expiration": "2022-12-15T17:08:58.535Z",
      "Status": "Email Not Sent",
      "Last Name": "PISTOLESI",
      "First Name": "GIULIA",
      "External Data Reference": "",
      "Email": "giulia.pistolesi@studenti.luiss.it",
      "Unsubscribed": false
    },
    {
      "Response Id": "",
      "Contact Id": "CID_9S3aOzE3lsndenA",
      "Link": "https://impresaluiss.qualtrics.com/jfe/form/SV_eScjs14ptWfE1Jc?Q_CHL=gl&Q_DL=WMyUUgKWyQwt6v0_eScjs14ptWfE1Jc_CGC_yy35QWgrTI1UkRj",
      "Exceeded Contact Frequency": false,
      "Link Expiration": "2022-12-15T17:08:58.535Z",
      "Status": "Email Not Sent",
      "Last Name": "WASSERMANN",
      "First Name": "LEA",
      "External Data Reference": "",
      "Email": "lea.wassermann@studenti.luiss.it",
      "Unsubscribed": false
    },
    {
      "Response Id": "",
      "Contact Id": "CID_eLHGXpHJpPLEtb8",
      "Link": "https://impresaluiss.qualtrics.com/jfe/form/SV_eScjs14ptWfE1Jc?Q_CHL=gl&Q_DL=WMyUUgKWyQwt6v0_eScjs14ptWfE1Jc_CGC_aVyoIaLyfIRBVef",
      "Exceeded Contact Frequency": false,
      "Link Expiration": "2022-12-15T17:08:58.535Z",
      "Status": "Email Not Sent",
      "Last Name": "IADEMARCO",
      "First Name": "ROBERTO",
      "External Data Reference": "",
      "Email": "roberto.iademarco@studenti.luiss.it",
      "Unsubscribed": false
    },
    {
      "Response Id": "",
      "Contact Id": "CID_6XKYiThw0vNI2dU",
      "Link": "https://impresaluiss.qualtrics.com/jfe/form/SV_eScjs14ptWfE1Jc?Q_CHL=gl&Q_DL=WMyUUgKWyQwt6v0_eScjs14ptWfE1Jc_CGC_DyGwaHJ0rYBSDhB",
      "Exceeded Contact Frequency": false,
      "Link Expiration": "2022-12-15T17:08:58.535Z",
      "Status": "Email Not Sent",
      "Last Name": "D'ARPINO",
      "First Name": "ILARIA",
      "External Data Reference": "",
      "Email": "ilaria.darpino@studenti.luiss.it",
      "Unsubscribed": false
    }
  ]